name: python_black_formatter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: set_up_python_${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black 
      - name: format_with_black
        run: |
         python -m black .
