name: unit_testing_validation
on: [pull_request, push]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-versions: [3.11]


    steps:
      - uses: actions/checkout@v2


      - name: sets_up_python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: x64


      - name: install_dependencies.
        run: | 
          pip3.11 install --upgrade pip
          pip3.11 install -r main_program/requirements.txt


      - name: run_unittests
        run: python3.11 -m unittest discover main_program/source/coding/test_suite/unit_tests
